spring:
  profiles:
    active: ${SPRING_PROFILE:dev}
  data:
    redis:
      host: host.docker.internal
      port: 6379
      password:
  datasource:
    url: jdbc:mysql://host.docker.internal:33060/stock-server?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  main:
    allow-bean-definition-overriding: true
  task:
    scheduling:
      pool:
        size: 10
  jackson:
    time-zone: Asia/Seoul

init:
  enabled : true

logging:
  file:
    name: /stock-logs/app.log # 이미 Dockerfile에서 -D로 설정했으므로 여기서는 선택 사항
  logback:
    rollingpolicy:
      max-file-size: 10MB # 각 로그 파일의 최대 크기
      max-history: 7 # 보관할 최대 파일 수
      total-size-cap: 100MB # 모든 보관된 로그 파일의 총 크기 제한

kis:
  clientId: client-0
  appkey: "PSD64gaxdXbILn8ad7LYQrKHujTVxlydAKiq"
  appsecret: "yHvyGFQiCbdmY8CXLe62/48/pID3JKOC7/4ElbdqnARCcDbmRwzB5idQ4HOTLGTEBUQIQN8X3L8xmoxa1jXZn80GXgl9DWZVfqKhxbYYfT6Nbnhvxdc4z9YW9/x6RCMWFEvZGwrFU/zoCJjA/21S/VCgbJ/P7mRPlbIADfFZx6b6kkTNvCE="
  grantType: client_credentials
  tokenUrl: https://openapi.koreainvestment.com:9443/oauth2/tokenP

server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    java:
      enabled: true
    os:
      enabled: true
data:
  service:
    key: 5n9IJueHw768SiRIOa9R0olMWrhJwyL7MizU9uL3DYjTmKZcW5z%2B%2F1M8mgyDI3WUcDa5kxgsSZj1tvdBjFOuRQ%3D%3D
